<a href="https://colab.research.google.com/github/uday-codes69/pytorch-foundations/blob/main/Copy_of_01_pytorch_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import torch
print(torch.__version__)

2.9.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name()}")
else:
  print("GPU is not available. Using CPU")

GPU is available
Using GPU: Tesla T4


# Creating a Tensor

In [ ]:
#using Empty
a = torch.empty(2,3)

In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using one
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(1,4)

tensor([[0.6765, 0.7539, 0.2627, 0.0428]])

In [ ]:
#using of seed
torch.manual_seed(42)
torch.rand(1,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593]])

In [ ]:
#manual seed
torch.manual_seed(100)
torch.rand(1,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839]])

In [ ]:
#manual seed
torch.manual_seed(100)
torch.rand(1,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#arange
print("using arrange :", torch.arange(2,10,2))

#using linspace
print("using linspace -> ", torch.linspace(0,10,10))

#using eye
print("using eye ->", torch.eye(5))

#using full
print("using full -> ", torch.full((3,3),5))

using arrange : tensor([2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
x = torch.tensor([[1,4,4],[2,3,1]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[    133880891190720,     133880891190720,               65536],
        [4681742012764214529,                  48,                 112]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[1., 4., 4.],
        [2., 3., 1.]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.6765, 0.7539, 0.2627],
        [0.0428, 0.2080, 0.1180]])
tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])


In [ ]:
#using multiplication
a ** b

#using division
a / b

tensor([[5.5590, 1.0249, 0.3691],
        [0.0544, 0.4973, 0.1309]])

In [ ]:
a % b

tensor([[0.0680, 0.0183, 0.2627],
        [0.0428, 0.2080, 0.1180]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.2,3.4,5.6,7.8])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 4., 6., 8.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 3., 5., 7.])

In [ ]:
#clamp
torch.clamp(d, min = 2, max=6)

tensor([2.0000, 3.4000, 5.6000, 6.0000])

# Reduction Operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high = 10,dtype=torch.float32)


In [ ]:
e

tensor([[1., 0., 4.],
        [3., 8., 7.]])

In [ ]:
torch.sum(e)
#sum along col
torch.sum(e,dim=0)
#sum along rows
torch.sum(e, dim =1)

tensor([ 5., 18.])

In [ ]:
#meam
torch.mean(e,dim=0)


#median
torch.median(e)

tensor(3.)

In [ ]:
#transpose
torch.transpose(e,0,1)

tensor([[1., 3.],
        [0., 8.],
        [4., 7.]])

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
#creating a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
#moving an existing tensor to gpu
a = torch.rand(2,3)
a

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])

In [ ]:
a.to(device)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]], device='cuda:0')

# Pytorch tensors & numpy

Numpy is a popular scientific python numerical computing library

Data in Numpy, want in Pytorch tensor -> torch.from_numpy(ndarray)

Pytorch Tensor -> Numpy -> torch.Tensor.numpy()

In [ ]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch numpy's default datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor = torch.arange(1.0, 8.0)
tensor.dtype

torch.float32

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
nump_tensor = tensor.numpy()
tensor, nump_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happen to numpy_tensor?
tensor = tensor+1
tensor, nump_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns

start with number -> take operations -> update random numbers to try and make them better representation of the data -> again -> again and again

To reduce the randomness in neural networks and pytorch come the concept of a **random seed**

In [ ]:
import torch

#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2426, 0.7003, 0.5277, 0.2472],
        [0.7909, 0.4235, 0.0169, 0.2209],
        [0.9535, 0.7064, 0.1629, 0.8902]])
tensor([[0.5163, 0.0359, 0.6476, 0.3430],
        [0.3182, 0.5261, 0.0447, 0.5123],
        [0.9051, 0.5989, 0.4450, 0.7278]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


*torch.manual_seed() fixes the starting point of PyTorch’s random number generator, ensuring reproducible random tensors across runs.*

**Same seed → same “random” sequence. &&
Different seed → different sequence**

In [ ]:
 1 == 1

True

In [ ]:
import torch

RANDOM_SEED = 47
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)


RANDOM_SEED = 47
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.0530, 0.0499, 0.4677, 0.8757],
        [0.5561, 0.7984, 0.9758, 0.2482],
        [0.1469, 0.4345, 0.6988, 0.8883]])
tensor([[0.0530, 0.0499, 0.4677, 0.8757],
        [0.5561, 0.7984, 0.9758, 0.2482],
        [0.1469, 0.4345, 0.6988, 0.8883]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
 #Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

False

In [ ]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [ ]:
import torch
tensor = torch.rand(7,7)
tensor

tensor([[2.6383e-01, 2.6581e-01, 1.3750e-01, 4.6097e-01, 7.4394e-01, 3.5056e-02,
         1.4224e-01],
        [4.0564e-01, 5.3406e-01, 5.8620e-01, 1.4691e-01, 2.9599e-01, 2.7384e-01,
         7.3611e-01],
        [9.1173e-01, 2.2841e-01, 5.9055e-02, 2.1353e-01, 4.8523e-01, 7.5743e-01,
         4.8650e-01],
        [8.5262e-02, 8.0155e-01, 7.4638e-01, 3.5573e-01, 4.0547e-01, 2.8260e-02,
         4.0705e-01],
        [3.2965e-01, 3.1501e-01, 5.4133e-01, 3.4997e-01, 2.9980e-01, 4.5799e-01,
         3.4092e-01],
        [3.9747e-01, 3.3840e-01, 3.7927e-01, 1.6479e-01, 6.7884e-04, 5.7458e-01,
         2.7804e-01],
        [4.2036e-01, 7.6008e-01, 2.3162e-01, 2.6895e-01, 4.6869e-01, 8.7141e-01,
         4.3764e-01]])

In [ ]:
torch.manual_seed(0)

A = torch.rand(7,7)
B = torch.rand(1,7)

result = torch.matmul( A, B.T)
result

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
torch.cuda.manual_seed(1234)
torch.cuda.manual_seed_all(1234)  # for multi-GPU

In [ ]:
result.argmax()

tensor(3)

In [ ]:
result.argmin()

tensor(4)

**Exercise Questions**

*Q1. Create a tensor of shape (3, 4) with random values and move it to GPU if available.*

In [ ]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.rand(3,4).to(device)
x

tensor([[0.8102, 0.9801, 0.1147, 0.3168],
        [0.6965, 0.9143, 0.9351, 0.9412],
        [0.5995, 0.0652, 0.5460, 0.1872]], device='cuda:0')

*Q2. What does requires_grad=True do?*

It tells PyTorch to track operations on the tensor so gradients can be computed during backpropagation.

*Q3. Difference between nn.Module and nn.Sequential?

Answer
	•	nn.Module → full control, custom forward
	•	nn.Sequential → quick stacking of layers
*

Q4. Perform matrix multiplication between tensors of shape (2,3) and (3,4).

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = torch.matmul(a, b)
c

tensor([[0.2927, 1.1014, 0.8939, 0.2576],
        [0.2263, 0.9299, 0.5019, 0.3497]])

In [ ]:
x = torch.rand(2, 3)
y = x.view(3, 2)
x
y

tensor([[0.9736, 0.8175],
        [0.9747, 0.4638],
        [0.0508, 0.2630]])